const trainingData = [
        {
                "id": 1,
                "title": "跨学科教学融合实践研修",
                "level": "市级培训",
                "year": 2025,
                "month": 7,
                "certificate": true,
                "hours": 18,
                "status": "已结束",
                "category1": "knowledge",
                "category2": "knowledge-subject",
                "dimension": "knowledge"
        },
        {
                "id": 2,
                "title": "新课标下的课堂教学创新培训",
                "level": "市级培训",
                "year": 2024,
                "month": 9,
                "certificate": true,
                "hours": 37,
                "status": "已结束",
                "category1": "ability",
                "category2": "ability-design",
                "dimension": "ability"
        },
        {
                "id": 3,
                "title": "心理健康教育与学生辅导培训",
                "level": "其它",
                "year": 2025,
                "month": 7,
                "certificate": true,
                "hours": 21,
                "status": "已结束",
                "category1": "ability",
                "category2": "ability-management",
                "dimension": "ability"
        },
        {
                "id": 4,
                "title": "学科核心考点解析与教学策略培训",
                "level": "国家级培训",
                "year": 2025,
                "month": 6,
                "certificate": true,
                "hours": 38,
                "status": "已结束",
                "category1": "knowledge",
                "category2": "knowledge-subject",
                "dimension": "knowledge"
        },
        {
                "id": 5,
                "title": "新课标下的课堂教学创新培训",
                "level": "其它",
                "year": 2024,
                "month": 6,
                "certificate": true,
                "hours": 32,
                "status": "已结束",
                "category1": "ability",
                "category2": "ability-design",
                "dimension": "ability"
        },
        {
                "id": 6,
                "title": "教育科研方法与论文写作培训",
                "level": "市级培训",
                "year": 2024,
                "month": 7,
                "certificate": true,
                "hours": 37,
                "status": "已结束",
                "category1": "ability",
                "category2": "ability-research",
                "dimension": "ability"
        },
        {
                "id": 7,
                "title": "教师信息技术应用能力提升培训",
                "level": "校级培训",
                "year": 2024,
                "month": 11,
                "certificate": true,
                "hours": 34,
                "status": "已结束",
                "category1": "digital",
                "category2": "digital-tech",
                "dimension": "digital"
        },
        {
                "id": 8,
                "title": "STEM教育理念与实践培训",
                "level": "国家级培训",
                "year": 2025,
                "month": 7,
                "certificate": true,
                "hours": 12,
                "status": "已结束",
                "category1": "ethics",
                "category2": "ethics-concept",
                "dimension": "ethics"
        },
        {
                "id": 9,
                "title": "新课标下的课堂教学创新培训",
                "level": "省级培训",
                "year": 2024,
                "month": 10,
                "certificate": true,
                "hours": 9,
                "status": "已结束",
                "category1": "ability",
                "category2": "ability-design",
                "dimension": "ability"
        },
        {
                "id": 10,
                "title": "教育科研方法与论文写作培训",
                "level": "市级培训",
                "year": 2024,
                "month": 6,
                "certificate": true,
                "hours": 40,
                "status": "已结束",
                "category1": "ability",
                "category2": "ability-research",
                "dimension": "ability"
        },
        {
                "id": 11,
                "title": "核心素养导向的教学设计培训",
                "level": "省级培训",
                "year": 2025,
                "month": 7,
                "certificate": true,
                "hours": 10,
                "status": "已结束",
                "category1": "ability",
                "category2": "ability-design",
                "dimension": "ability"
        },
        {
                "id": 12,
                "title": "核心素养导向的教学设计培训",
                "level": "市级培训",
                "year": 2025,
                "month": 12,
                "certificate": true,
                "hours": 16,
                "status": "已结束",
                "category1": "ability",
                "category2": "ability-design",
                "dimension": "ability"
        },
        {
                "id": 13,
                "title": "特殊学生教育与帮扶培训",
                "level": "国家级培训",
                "year": 2025,
                "month": 1,
                "certificate": true,
                "hours": 40,
                "status": "已结束",
                "category1": "ability",
                "category2": "ability-management",
                "dimension": "ability"
        },
        {
                "id": 14,
                "title": "心理健康教育与学生辅导培训",
                "level": "市级培训",
                "year": 2023,
                "month": 8,
                "certificate": true,
                "hours": 45,
                "status": "已结束",
                "category1": "ability",
                "category2": "ability-management",
                "dimension": "ability"
        },
        {
                "id": 15,
                "title": "教育科研方法与论文写作培训",
                "level": "校级培训",
                "year": 2023,
                "month": 3,
                "certificate": true,
                "hours": 34,
                "status": "已结束",
                "category1": "ability",
                "category2": "ability-research",
                "dimension": "ability"
        },
        {
                "id": 16,
                "title": "特殊学生教育与帮扶培训",
                "level": "国家级培训",
                "year": 2025,
                "month": 6,
                "certificate": true,
                "hours": 32,
                "status": "已结束",
                "category1": "ability",
                "category2": "ability-management",
                "dimension": "ability"
        },
        {
                "id": 17,
                "title": "师德师风建设专题培训",
                "level": "省级培训",
                "year": 2024,
                "month": 5,
                "certificate": true,
                "hours": 46,
                "status": "已结束",
                "category1": "ethics",
                "category2": "ethics-cultivation",
                "dimension": "ethics"
        },
        {
                "id": 18,
                "title": "作业设计与评价改革培训",
                "level": "校级培训",
                "year": 2024,
                "month": 11,
                "certificate": true,
                "hours": 40,
                "status": "已结束",
                "category1": "ability",
                "category2": "ability-design",
                "dimension": "ability"
        },
        {
                "id": 19,
                "title": "智慧课堂建设与应用培训",
                "level": "国家级培训",
                "year": 2024,
                "month": 5,
                "certificate": true,
                "hours": 20,
                "status": "已结束",
                "category1": "digital",
                "category2": "digital-tech",
                "dimension": "digital"
        },
        {
                "id": 20,
                "title": "班主任班级管理能力研修",
                "level": "校级培训",
                "year": 2024,
                "month": 2,
                "certificate": true,
                "hours": 6,
                "status": "已结束",
                "category1": "ability",
                "category2": "ability-management",
                "dimension": "ability"
        },
        {
                "id": 21,
                "title": "特殊学生教育与帮扶培训",
                "level": "市级培训",
                "year": 2023,
                "month": 11,
                "certificate": true,
                "hours": 40,
                "status": "已结束",
                "category1": "ability",
                "category2": "ability-management",
                "dimension": "ability"
        },
        {
                "id": 22,
                "title": "作业设计与评价改革培训",
                "level": "校级培训",
                "year": 2025,
                "month": 9,
                "certificate": true,
                "hours": 11,
                "status": "已结束",
                "category1": "ability",
                "category2": "ability-design",
                "dimension": "ability"
        },
        {
                "id": 23,
                "title": "教师信息技术应用能力提升培训",
                "level": "其它",
                "year": 2023,
                "month": 3,
                "certificate": true,
                "hours": 17,
                "status": "已结束",
                "category1": "digital",
                "category2": "digital-tech",
                "dimension": "digital"
        },
        {
                "id": 24,
                "title": "班主任班级管理能力研修",
                "level": "省级培训",
                "year": 2024,
                "month": 3,
                "certificate": true,
                "hours": 9,
                "status": "已结束",
                "category1": "ability",
                "category2": "ability-management",
                "dimension": "ability"
        },
        {
                "id": 25,
                "title": "作业设计与评价改革培训",
                "level": "国家级培训",
                "year": 2024,
                "month": 7,
                "certificate": true,
                "hours": 15,
                "status": "已结束",
                "category1": "ability",
                "category2": "ability-design",
                "dimension": "ability"
        },
        {
                "id": 26,
                "title": "班主任班级管理能力研修",
                "level": "省级培训",
                "year": 2023,
                "month": 2,
                "certificate": true,
                "hours": 22,
                "status": "已结束",
                "category1": "ability",
                "category2": "ability-management",
                "dimension": "ability"
        },
        {
                "id": 27,
                "title": "校本课程开发与实施培训",
                "level": "国家级培训",
                "year": 2023,
                "month": 4,
                "certificate": true,
                "hours": 28,
                "status": "已结束",
                "category1": "ability",
                "category2": "ability-development",
                "dimension": "ability"
        },
        {
                "id": 28,
                "title": "教师信息技术应用能力提升培训",
                "level": "省级培训",
                "year": 2023,
                "month": 12,
                "certificate": true,
                "hours": 27,
                "status": "已结束",
                "category1": "digital",
                "category2": "digital-tech",
                "dimension": "digital"
        },
        {
                "id": 29,
                "title": "新课标下的课堂教学创新培训",
                "level": "校级培训",
                "year": 2024,
                "month": 1,
                "certificate": true,
                "hours": 38,
                "status": "已结束",
                "category1": "ability",
                "category2": "ability-design",
                "dimension": "ability"
        },
        {
                "id": 30,
                "title": "核心素养导向的教学设计培训",
                "level": "其它",
                "year": 2025,
                "month": 4,
                "certificate": true,
                "hours": 43,
                "status": "已结束",
                "category1": "ability",
                "category2": "ability-design",
                "dimension": "ability"
        },
        {
                "id": 31,
                "title": "STEM教育理念与实践培训",
                "level": "市级培训",
                "year": 2024,
                "month": 3,
                "certificate": true,
                "hours": 7,
                "status": "已结束",
                "category1": "ethics",
                "category2": "ethics-concept",
                "dimension": "ethics"
        },
        {
                "id": 32,
                "title": "作业设计与评价改革培训",
                "level": "校级培训",
                "year": 2023,
                "month": 9,
                "certificate": true,
                "hours": 16,
                "status": "已结束",
                "category1": "ability",
                "category2": "ability-design",
                "dimension": "ability"
        },
        {
                "id": 33,
                "title": "家校共育沟通技巧培训",
                "level": "国家级培训",
                "year": 2025,
                "month": 4,
                "certificate": true,
                "hours": 30,
                "status": "已结束",
                "category1": "ability",
                "category2": "ability-management",
                "dimension": "ability"
        },
        {
                "id": 34,
                "title": "班主任班级管理能力研修",
                "level": "市级培训",
                "year": 2023,
                "month": 7,
                "certificate": true,
                "hours": 44,
                "status": "已结束",
                "category1": "ability",
                "category2": "ability-management",
                "dimension": "ability"
        },
        {
                "id": 35,
                "title": "STEM教育理念与实践培训",
                "level": "国家级培训",
                "year": 2024,
                "month": 9,
                "certificate": true,
                "hours": 44,
                "status": "已结束",
                "category1": "ethics",
                "category2": "ethics-concept",
                "dimension": "ethics"
        },
        {
                "id": 36,
                "title": "师德师风建设专题培训",
                "level": "国家级培训",
                "year": 2025,
                "month": 6,
                "certificate": true,
                "hours": 43,
                "status": "已结束",
                "category1": "ethics",
                "category2": "ethics-cultivation",
                "dimension": "ethics"
        },
        {
                "id": 37,
                "title": "心理健康教育与学生辅导培训",
                "level": "市级培训",
                "year": 2023,
                "month": 10,
                "certificate": true,
                "hours": 45,
                "status": "已结束",
                "category1": "ability",
                "category2": "ability-management",
                "dimension": "ability"
        },
        {
                "id": 38,
                "title": "作业设计与评价改革培训",
                "level": "市级培训",
                "year": 2023,
                "month": 7,
                "certificate": true,
                "hours": 10,
                "status": "已结束",
                "category1": "ability",
                "category2": "ability-design",
                "dimension": "ability"
        },
        {
                "id": 39,
                "title": "学科核心考点解析与教学策略培训",
                "level": "其它",
                "year": 2023,
                "month": 5,
                "certificate": true,
                "hours": 48,
                "status": "已结束",
                "category1": "knowledge",
                "category2": "knowledge-subject",
                "dimension": "knowledge"
        },
        {
                "id": 40,
                "title": "校本课程开发与实施培训",
                "level": "国家级培训",
                "year": 2024,
                "month": 5,
                "certificate": true,
                "hours": 9,
                "status": "已结束",
                "category1": "ability",
                "category2": "ability-development",
                "dimension": "ability"
        },
        {
                "id": 41,
                "title": "特殊学生教育与帮扶培训",
                "level": "其它",
                "year": 2023,
                "month": 10,
                "certificate": true,
                "hours": 35,
                "status": "已结束",
                "category1": "ability",
                "category2": "ability-management",
                "dimension": "ability"
        },
        {
                "id": 42,
                "title": "学科核心考点解析与教学策略培训",
                "level": "省级培训",
                "year": 2024,
                "month": 3,
                "certificate": true,
                "hours": 19,
                "status": "已结束",
                "category1": "knowledge",
                "category2": "knowledge-subject",
                "dimension": "knowledge"
        },
        {
                "id": 43,
                "title": "教育科研方法与论文写作培训",
                "level": "其它",
                "year": 2024,
                "month": 4,
                "certificate": true,
                "hours": 16,
                "status": "已结束",
                "category1": "ability",
                "category2": "ability-research",
                "dimension": "ability"
        },
        {
                "id": 44,
                "title": "跨学科教学融合实践研修",
                "level": "其它",
                "year": 2024,
                "month": 2,
                "certificate": true,
                "hours": 42,
                "status": "已结束",
                "category1": "knowledge",
                "category2": "knowledge-subject",
                "dimension": "knowledge"
        },
        {
                "id": 45,
                "title": "STEM教育理念与实践培训",
                "level": "其它",
                "year": 2025,
                "month": 11,
                "certificate": true,
                "hours": 15,
                "status": "已结束",
                "category1": "ethics",
                "category2": "ethics-concept",
                "dimension": "ethics"
        },
        {
                "id": 46,
                "title": "智慧课堂建设与应用培训",
                "level": "其它",
                "year": 2025,
                "month": 9,
                "certificate": true,
                "hours": 13,
                "status": "已结束",
                "category1": "digital",
                "category2": "digital-tech",
                "dimension": "digital"
        },
        {
                "id": 47,
                "title": "班主任班级管理能力研修",
                "level": "国家级培训",
                "year": 2024,
                "month": 5,
                "certificate": true,
                "hours": 43,
                "status": "已结束",
                "category1": "ability",
                "category2": "ability-management",
                "dimension": "ability"
        },
        {
                "id": 48,
                "title": "STEM教育理念与实践培训",
                "level": "国家级培训",
                "year": 2023,
                "month": 3,
                "certificate": true,
                "hours": 16,
                "status": "已结束",
                "category1": "ethics",
                "category2": "ethics-concept",
                "dimension": "ethics"
        },
        {
                "id": 49,
                "title": "核心素养导向的教学设计培训",
                "level": "省级培训",
                "year": 2025,
                "month": 7,
                "certificate": true,
                "hours": 38,
                "status": "已结束",
                "category1": "ability",
                "category2": "ability-design",
                "dimension": "ability"
        },
        {
                "id": 50,
                "title": "校本课程开发与实施培训",
                "level": "国家级培训",
                "year": 2023,
                "month": 3,
                "certificate": true,
                "hours": 39,
                "status": "已结束",
                "category1": "ability",
                "category2": "ability-development",
                "dimension": "ability"
        },
        {
                "id": 51,
                "title": "班主任班级管理能力研修",
                "level": "校级培训",
                "year": 2025,
                "month": 2,
                "certificate": true,
                "hours": 37,
                "status": "已结束",
                "category1": "ability",
                "category2": "ability-management",
                "dimension": "ability"
        },
        {
                "id": 52,
                "title": "教师信息技术应用能力提升培训",
                "level": "其它",
                "year": 2025,
                "month": 6,
                "certificate": true,
                "hours": 42,
                "status": "已结束",
                "category1": "digital",
                "category2": "digital-tech",
                "dimension": "digital"
        },
        {
                "id": 53,
                "title": "学科核心考点解析与教学策略培训",
                "level": "市级培训",
                "year": 2024,
                "month": 3,
                "certificate": true,
                "hours": 34,
                "status": "已结束",
                "category1": "knowledge",
                "category2": "knowledge-subject",
                "dimension": "knowledge"
        },
        {
                "id": 54,
                "title": "智慧课堂建设与应用培训",
                "level": "校级培训",
                "year": 2024,
                "month": 10,
                "certificate": true,
                "hours": 23,
                "status": "已结束",
                "category1": "digital",
                "category2": "digital-tech",
                "dimension": "digital"
        },
        {
                "id": 55,
                "title": "家校共育沟通技巧培训",
                "level": "市级培训",
                "year": 2025,
                "month": 5,
                "certificate": true,
                "hours": 37,
                "status": "已结束",
                "category1": "ability",
                "category2": "ability-management",
                "dimension": "ability"
        },
        {
                "id": 56,
                "title": "师德师风建设专题培训",
                "level": "其它",
                "year": 2024,
                "month": 6,
                "certificate": true,
                "hours": 21,
                "status": "已结束",
                "category1": "ethics",
                "category2": "ethics-cultivation",
                "dimension": "ethics"
        },
        {
                "id": 57,
                "title": "作业设计与评价改革培训",
                "level": "省级培训",
                "year": 2024,
                "month": 7,
                "certificate": true,
                "hours": 9,
                "status": "已结束",
                "category1": "ability",
                "category2": "ability-design",
                "dimension": "ability"
        },
        {
                "id": 58,
                "title": "新课标下的课堂教学创新培训",
                "level": "市级培训",
                "year": 2025,
                "month": 4,
                "certificate": true,
                "hours": 19,
                "status": "已结束",
                "category1": "ability",
                "category2": "ability-design",
                "dimension": "ability"
        },
        {
                "id": 59,
                "title": "STEM教育理念与实践培训",
                "level": "国家级培训",
                "year": 2023,
                "month": 3,
                "certificate": true,
                "hours": 44,
                "status": "已结束",
                "category1": "ethics",
                "category2": "ethics-concept",
                "dimension": "ethics"
        },
        {
                "id": 60,
                "title": "作业设计与评价改革培训",
                "level": "其它",
                "year": 2025,
                "month": 9,
                "certificate": true,
                "hours": 21,
                "status": "已结束",
                "category1": "ability",
                "category2": "ability-design",
                "dimension": "ability"
        },
        {
                "id": 61,
                "title": "教师信息技术应用能力提升培训",
                "level": "其它",
                "year": 2024,
                "month": 11,
                "certificate": true,
                "hours": 14,
                "status": "已结束",
                "category1": "digital",
                "category2": "digital-tech",
                "dimension": "digital"
        },
        {
                "id": 62,
                "title": "作业设计与评价改革培训",
                "level": "市级培训",
                "year": 2024,
                "month": 6,
                "certificate": true,
                "hours": 18,
                "status": "已结束",
                "category1": "ability",
                "category2": "ability-design",
                "dimension": "ability"
        },
        {
                "id": 63,
                "title": "STEM教育理念与实践培训",
                "level": "省级培训",
                "year": 2023,
                "month": 9,
                "certificate": true,
                "hours": 7,
                "status": "已结束",
                "category1": "ethics",
                "category2": "ethics-concept",
                "dimension": "ethics"
        },
        {
                "id": 64,
                "title": "校本课程开发与实施培训",
                "level": "校级培训",
                "year": 2025,
                "month": 7,
                "certificate": true,
                "hours": 7,
                "status": "已结束",
                "category1": "ability",
                "category2": "ability-development",
                "dimension": "ability"
        },
        {
                "id": 65,
                "title": "教师信息技术应用能力提升培训",
                "level": "市级培训",
                "year": 2023,
                "month": 10,
                "certificate": true,
                "hours": 12,
                "status": "已结束",
                "category1": "digital",
                "category2": "digital-tech",
                "dimension": "digital"
        },
        {
                "id": 66,
                "title": "智慧课堂建设与应用培训",
                "level": "其它",
                "year": 2025,
                "month": 10,
                "certificate": true,
                "hours": 38,
                "status": "已结束",
                "category1": "digital",
                "category2": "digital-tech",
                "dimension": "digital"
        },
        {
                "id": 67,
                "title": "教育科研方法与论文写作培训",
                "level": "其它",
                "year": 2023,
                "month": 1,
                "certificate": true,
                "hours": 37,
                "status": "已结束",
                "category1": "ability",
                "category2": "ability-research",
                "dimension": "ability"
        },
        {
                "id": 68,
                "title": "跨学科教学融合实践研修",
                "level": "省级培训",
                "year": 2023,
                "month": 7,
                "certificate": true,
                "hours": 37,
                "status": "已结束",
                "category1": "knowledge",
                "category2": "knowledge-subject",
                "dimension": "knowledge"
        },
        {
                "id": 69,
                "title": "特殊学生教育与帮扶培训",
                "level": "市级培训",
                "year": 2025,
                "month": 2,
                "certificate": true,
                "hours": 33,
                "status": "已结束",
                "category1": "ability",
                "category2": "ability-management",
                "dimension": "ability"
        },
        {
                "id": 70,
                "title": "核心素养导向的教学设计培训",
                "level": "其它",
                "year": 2024,
                "month": 9,
                "certificate": true,
                "hours": 35,
                "status": "已结束",
                "category1": "ability",
                "category2": "ability-design",
                "dimension": "ability"
        },
        {
                "id": 71,
                "title": "师德师风建设专题培训",
                "level": "市级培训",
                "year": 2024,
                "month": 3,
                "certificate": true,
                "hours": 27,
                "status": "已结束",
                "category1": "ethics",
                "category2": "ethics-cultivation",
                "dimension": "ethics"
        },
        {
                "id": 72,
                "title": "教育科研方法与论文写作培训",
                "level": "市级培训",
                "year": 2023,
                "month": 10,
                "certificate": true,
                "hours": 47,
                "status": "已结束",
                "category1": "ability",
                "category2": "ability-research",
                "dimension": "ability"
        },
        {
                "id": 73,
                "title": "校本课程开发与实施培训",
                "level": "其它",
                "year": 2023,
                "month": 10,
                "certificate": true,
                "hours": 40,
                "status": "已结束",
                "category1": "ability",
                "category2": "ability-development",
                "dimension": "ability"
        },
        {
                "id": 74,
                "title": "新课标下的课堂教学创新培训",
                "level": "国家级培训",
                "year": 2024,
                "month": 6,
                "certificate": true,
                "hours": 22,
                "status": "已结束",
                "category1": "ability",
                "category2": "ability-design",
                "dimension": "ability"
        },
        {
                "id": 75,
                "title": "校本课程开发与实施培训",
                "level": "省级培训",
                "year": 2023,
                "month": 12,
                "certificate": true,
                "hours": 18,
                "status": "已结束",
                "category1": "ability",
                "category2": "ability-development",
                "dimension": "ability"
        },
        {
                "id": 76,
                "title": "作业设计与评价改革培训",
                "level": "国家级培训",
                "year": 2025,
                "month": 4,
                "certificate": true,
                "hours": 36,
                "status": "已结束",
                "category1": "ability",
                "category2": "ability-design",
                "dimension": "ability"
        },
        {
                "id": 77,
                "title": "师德师风建设专题培训",
                "level": "其它",
                "year": 2025,
                "month": 1,
                "certificate": true,
                "hours": 4,
                "status": "已结束",
                "category1": "ethics",
                "category2": "ethics-cultivation",
                "dimension": "ethics"
        },
        {
                "id": 78,
                "title": "教育科研方法与论文写作培训",
                "level": "其它",
                "year": 2023,
                "month": 6,
                "certificate": true,
                "hours": 8,
                "status": "已结束",
                "category1": "ability",
                "category2": "ability-research",
                "dimension": "ability"
        },
        {
                "id": 79,
                "title": "教育科研方法与论文写作培训",
                "level": "省级培训",
                "year": 2023,
                "month": 1,
                "certificate": true,
                "hours": 15,
                "status": "已结束",
                "category1": "ability",
                "category2": "ability-research",
                "dimension": "ability"
        },
        {
                "id": 80,
                "title": "STEM教育理念与实践培训",
                "level": "市级培训",
                "year": 2024,
                "month": 2,
                "certificate": true,
                "hours": 19,
                "status": "已结束",
                "category1": "ethics",
                "category2": "ethics-concept",
                "dimension": "ethics"
        },
        {
                "id": 81,
                "title": "校本课程开发与实施培训",
                "level": "其它",
                "year": 2024,
                "month": 10,
                "certificate": true,
                "hours": 30,
                "status": "已结束",
                "category1": "ability",
                "category2": "ability-development",
                "dimension": "ability"
        },
        {
                "id": 82,
                "title": "核心素养导向的教学设计培训",
                "level": "校级培训",
                "year": 2024,
                "month": 8,
                "certificate": true,
                "hours": 43,
                "status": "已结束",
                "category1": "ability",
                "category2": "ability-design",
                "dimension": "ability"
        },
        {
                "id": 83,
                "title": "作业设计与评价改革培训",
                "level": "校级培训",
                "year": 2025,
                "month": 5,
                "certificate": true,
                "hours": 8,
                "status": "已结束",
                "category1": "ability",
                "category2": "ability-design",
                "dimension": "ability"
        },
        {
                "id": 84,
                "title": "新课标下的课堂教学创新培训",
                "level": "市级培训",
                "year": 2023,
                "month": 6,
                "certificate": true,
                "hours": 44,
                "status": "已结束",
                "category1": "ability",
                "category2": "ability-design",
                "dimension": "ability"
        },
        {
                "id": 85,
                "title": "智慧课堂建设与应用培训",
                "level": "校级培训",
                "year": 2024,
                "month": 1,
                "certificate": true,
                "hours": 31,
                "status": "已结束",
                "category1": "digital",
                "category2": "digital-tech",
                "dimension": "digital"
        },
        {
                "id": 86,
                "title": "智慧课堂建设与应用培训",
                "level": "市级培训",
                "year": 2024,
                "month": 9,
                "certificate": true,
                "hours": 48,
                "status": "已结束",
                "category1": "digital",
                "category2": "digital-tech",
                "dimension": "digital"
        },
        {
                "id": 87,
                "title": "班主任班级管理能力研修",
                "level": "校级培训",
                "year": 2025,
                "month": 8,
                "certificate": true,
                "hours": 22,
                "status": "已结束",
                "category1": "ability",
                "category2": "ability-management",
                "dimension": "ability"
        },
        {
                "id": 88,
                "title": "STEM教育理念与实践培训",
                "level": "校级培训",
                "year": 2025,
                "month": 5,
                "certificate": true,
                "hours": 43,
                "status": "已结束",
                "category1": "ethics",
                "category2": "ethics-concept",
                "dimension": "ethics"
        },
        {
                "id": 89,
                "title": "智慧课堂建设与应用培训",
                "level": "省级培训",
                "year": 2025,
                "month": 3,
                "certificate": true,
                "hours": 27,
                "status": "已结束",
                "category1": "digital",
                "category2": "digital-tech",
                "dimension": "digital"
        },
        {
                "id": 90,
                "title": "家校共育沟通技巧培训",
                "level": "省级培训",
                "year": 2023,
                "month": 12,
                "certificate": true,
                "hours": 31,
                "status": "已结束",
                "category1": "ability",
                "category2": "ability-management",
                "dimension": "ability"
        },
        {
                "id": 91,
                "title": "学科核心考点解析与教学策略培训",
                "level": "校级培训",
                "year": 2023,
                "month": 9,
                "certificate": true,
                "hours": 10,
                "status": "已结束",
                "category1": "knowledge",
                "category2": "knowledge-subject",
                "dimension": "knowledge"
        },
        {
                "id": 92,
                "title": "心理健康教育与学生辅导培训",
                "level": "国家级培训",
                "year": 2025,
                "month": 11,
                "certificate": true,
                "hours": 15,
                "status": "已结束",
                "category1": "ability",
                "category2": "ability-management",
                "dimension": "ability"
        },
        {
                "id": 93,
                "title": "跨学科教学融合实践研修",
                "level": "市级培训",
                "year": 2023,
                "month": 10,
                "certificate": true,
                "hours": 13,
                "status": "已结束",
                "category1": "knowledge",
                "category2": "knowledge-subject",
                "dimension": "knowledge"
        },
        {
                "id": 94,
                "title": "学科核心考点解析与教学策略培训",
                "level": "校级培训",
                "year": 2025,
                "month": 5,
                "certificate": true,
                "hours": 14,
                "status": "已结束",
                "category1": "knowledge",
                "category2": "knowledge-subject",
                "dimension": "knowledge"
        },
        {
                "id": 95,
                "title": "教师信息技术应用能力提升培训",
                "level": "省级培训",
                "year": 2024,
                "month": 3,
                "certificate": true,
                "hours": 46,
                "status": "已结束",
                "category1": "digital",
                "category2": "digital-tech",
                "dimension": "digital"
        },
        {
                "id": 96,
                "title": "核心素养导向的教学设计培训",
                "level": "国家级培训",
                "year": 2025,
                "month": 1,
                "certificate": true,
                "hours": 28,
                "status": "已结束",
                "category1": "ability",
                "category2": "ability-design",
                "dimension": "ability"
        },
        {
                "id": 97,
                "title": "家校共育沟通技巧培训",
                "level": "国家级培训",
                "year": 2025,
                "month": 6,
                "certificate": true,
                "hours": 21,
                "status": "已结束",
                "category1": "ability",
                "category2": "ability-management",
                "dimension": "ability"
        },
        {
                "id": 98,
                "title": "班主任班级管理能力研修",
                "level": "省级培训",
                "year": 2024,
                "month": 1,
                "certificate": true,
                "hours": 18,
                "status": "已结束",
                "category1": "ability",
                "category2": "ability-management",
                "dimension": "ability"
        },
        {
                "id": 99,
                "title": "心理健康教育与学生辅导培训",
                "level": "省级培训",
                "year": 2023,
                "month": 1,
                "certificate": true,
                "hours": 30,
                "status": "已结束",
                "category1": "ability",
                "category2": "ability-management",
                "dimension": "ability"
        },
        {
                "id": 100,
                "title": "校本课程开发与实施培训",
                "level": "校级培训",
                "year": 2024,
                "month": 4,
                "certificate": true,
                "hours": 20,
                "status": "已结束",
                "category1": "ability",
                "category2": "ability-development",
                "dimension": "ability"
        },
        {
                "id": 101,
                "title": "师德师风建设专题培训",
                "level": "其它",
                "year": 2023,
                "month": 4,
                "certificate": true,
                "hours": 7,
                "status": "已结束",
                "category1": "ethics",
                "category2": "ethics-cultivation",
                "dimension": "ethics"
        },
        {
                "id": 102,
                "title": "STEM教育理念与实践培训",
                "level": "国家级培训",
                "year": 2025,
                "month": 7,
                "certificate": true,
                "hours": 41,
                "status": "已结束",
                "category1": "ethics",
                "category2": "ethics-concept",
                "dimension": "ethics"
        },
        {
                "id": 103,
                "title": "智慧课堂建设与应用培训",
                "level": "国家级培训",
                "year": 2023,
                "month": 5,
                "certificate": true,
                "hours": 4,
                "status": "已结束",
                "category1": "digital",
                "category2": "digital-tech",
                "dimension": "digital"
        },
        {
                "id": 104,
                "title": "心理健康教育与学生辅导培训",
                "level": "其它",
                "year": 2023,
                "month": 12,
                "certificate": true,
                "hours": 38,
                "status": "已结束",
                "category1": "ability",
                "category2": "ability-management",
                "dimension": "ability"
        },
        {
                "id": 105,
                "title": "教育科研方法与论文写作培训",
                "level": "国家级培训",
                "year": 2024,
                "month": 7,
                "certificate": true,
                "hours": 16,
                "status": "已结束",
                "category1": "ability",
                "category2": "ability-research",
                "dimension": "ability"
        },
        {
                "id": 106,
                "title": "作业设计与评价改革培训",
                "level": "国家级培训",
                "year": 2023,
                "month": 6,
                "certificate": true,
                "hours": 29,
                "status": "已结束",
                "category1": "ability",
                "category2": "ability-design",
                "dimension": "ability"
        },
        {
                "id": 107,
                "title": "学科核心考点解析与教学策略培训",
                "level": "校级培训",
                "year": 2023,
                "month": 4,
                "certificate": true,
                "hours": 19,
                "status": "已结束",
                "category1": "knowledge",
                "category2": "knowledge-subject",
                "dimension": "knowledge"
        },
        {
                "id": 108,
                "title": "教育科研方法与论文写作培训",
                "level": "市级培训",
                "year": 2025,
                "month": 11,
                "certificate": true,
                "hours": 30,
                "status": "已结束",
                "category1": "ability",
                "category2": "ability-research",
                "dimension": "ability"
        },
        {
                "id": 109,
                "title": "STEM教育理念与实践培训",
                "level": "省级培训",
                "year": 2023,
                "month": 8,
                "certificate": true,
                "hours": 29,
                "status": "已结束",
                "category1": "ethics",
                "category2": "ethics-concept",
                "dimension": "ethics"
        },
        {
                "id": 110,
                "title": "作业设计与评价改革培训",
                "level": "校级培训",
                "year": 2024,
                "month": 6,
                "certificate": true,
                "hours": 19,
                "status": "已结束",
                "category1": "ability",
                "category2": "ability-design",
                "dimension": "ability"
        },
        {
                "id": 111,
                "title": "师德师风建设专题培训",
                "level": "市级培训",
                "year": 2023,
                "month": 8,
                "certificate": true,
                "hours": 40,
                "status": "已结束",
                "category1": "ethics",
                "category2": "ethics-cultivation",
                "dimension": "ethics"
        },
        {
                "id": 112,
                "title": "教育科研方法与论文写作培训",
                "level": "市级培训",
                "year": 2025,
                "month": 11,
                "certificate": true,
                "hours": 41,
                "status": "已结束",
                "category1": "ability",
                "category2": "ability-research",
                "dimension": "ability"
        },
        {
                "id": 113,
                "title": "跨学科教学融合实践研修",
                "level": "省级培训",
                "year": 2025,
                "month": 8,
                "certificate": true,
                "hours": 26,
                "status": "已结束",
                "category1": "knowledge",
                "category2": "knowledge-subject",
                "dimension": "knowledge"
        },
        {
                "id": 114,
                "title": "核心素养导向的教学设计培训",
                "level": "国家级培训",
                "year": 2025,
                "month": 6,
                "certificate": true,
                "hours": 45,
                "status": "已结束",
                "category1": "ability",
                "category2": "ability-design",
                "dimension": "ability"
        },
        {
                "id": 115,
                "title": "特殊学生教育与帮扶培训",
                "level": "市级培训",
                "year": 2023,
                "month": 8,
                "certificate": true,
                "hours": 40,
                "status": "已结束",
                "category1": "ability",
                "category2": "ability-management",
                "dimension": "ability"
        },
        {
                "id": 116,
                "title": "家校共育沟通技巧培训",
                "level": "其它",
                "year": 2024,
                "month": 3,
                "certificate": true,
                "hours": 48,
                "status": "已结束",
                "category1": "ability",
                "category2": "ability-management",
                "dimension": "ability"
        },
        {
                "id": 117,
                "title": "家校共育沟通技巧培训",
                "level": "国家级培训",
                "year": 2023,
                "month": 6,
                "certificate": true,
                "hours": 7,
                "status": "已结束",
                "category1": "ability",
                "category2": "ability-management",
                "dimension": "ability"
        },
        {
                "id": 118,
                "title": "STEM教育理念与实践培训",
                "level": "国家级培训",
                "year": 2024,
                "month": 10,
                "certificate": true,
                "hours": 34,
                "status": "已结束",
                "category1": "ethics",
                "category2": "ethics-concept",
                "dimension": "ethics"
        },
        {
                "id": 119,
                "title": "新课标下的课堂教学创新培训",
                "level": "国家级培训",
                "year": 2024,
                "month": 7,
                "certificate": true,
                "hours": 28,
                "status": "已结束",
                "category1": "ability",
                "category2": "ability-design",
                "dimension": "ability"
        },
        {
                "id": 120,
                "title": "教师信息技术应用能力提升培训",
                "level": "校级培训",
                "year": 2023,
                "month": 9,
                "certificate": true,
                "hours": 14,
                "status": "已结束",
                "category1": "digital",
                "category2": "digital-tech",
                "dimension": "digital"
        },
        {
                "id": 121,
                "title": "智慧课堂建设与应用培训",
                "level": "校级培训",
                "year": 2025,
                "month": 8,
                "certificate": true,
                "hours": 13,
                "status": "已结束",
                "category1": "digital",
                "category2": "digital-tech",
                "dimension": "digital"
        },
        {
                "id": 122,
                "title": "特殊学生教育与帮扶培训",
                "level": "国家级培训",
                "year": 2024,
                "month": 10,
                "certificate": true,
                "hours": 33,
                "status": "已结束",
                "category1": "ability",
                "category2": "ability-management",
                "dimension": "ability"
        },
        {
                "id": 123,
                "title": "智慧课堂建设与应用培训",
                "level": "市级培训",
                "year": 2023,
                "month": 12,
                "certificate": true,
                "hours": 15,
                "status": "已结束",
                "category1": "digital",
                "category2": "digital-tech",
                "dimension": "digital"
        },
        {
                "id": 124,
                "title": "智慧课堂建设与应用培训",
                "level": "其它",
                "year": 2023,
                "month": 6,
                "certificate": true,
                "hours": 23,
                "status": "已结束",
                "category1": "digital",
                "category2": "digital-tech",
                "dimension": "digital"
        },
        {
                "id": 125,
                "title": "心理健康教育与学生辅导培训",
                "level": "省级培训",
                "year": 2025,
                "month": 4,
                "certificate": true,
                "hours": 40,
                "status": "已结束",
                "category1": "ability",
                "category2": "ability-management",
                "dimension": "ability"
        },
        {
                "id": 126,
                "title": "核心素养导向的教学设计培训",
                "level": "校级培训",
                "year": 2025,
                "month": 4,
                "certificate": true,
                "hours": 27,
                "status": "已结束",
                "category1": "ability",
                "category2": "ability-design",
                "dimension": "ability"
        },
        {
                "id": 127,
                "title": "教师信息技术应用能力提升培训",
                "level": "校级培训",
                "year": 2024,
                "month": 3,
                "certificate": true,
                "hours": 37,
                "status": "已结束",
                "category1": "digital",
                "category2": "digital-tech",
                "dimension": "digital"
        },
        {
                "id": 128,
                "title": "校本课程开发与实施培训",
                "level": "其它",
                "year": 2025,
                "month": 8,
                "certificate": true,
                "hours": 9,
                "status": "已结束",
                "category1": "ability",
                "category2": "ability-development",
                "dimension": "ability"
        },
        {
                "id": 129,
                "title": "教师信息技术应用能力提升培训",
                "level": "其它",
                "year": 2025,
                "month": 12,
                "certificate": true,
                "hours": 22,
                "status": "已结束",
                "category1": "digital",
                "category2": "digital-tech",
                "dimension": "digital"
        },
        {
                "id": 130,
                "title": "跨学科教学融合实践研修",
                "level": "国家级培训",
                "year": 2025,
                "month": 10,
                "certificate": true,
                "hours": 4,
                "status": "已结束",
                "category1": "knowledge",
                "category2": "knowledge-subject",
                "dimension": "knowledge"
        },
        {
                "id": 131,
                "title": "师德师风建设专题培训",
                "level": "国家级培训",
                "year": 2023,
                "month": 3,
                "certificate": true,
                "hours": 34,
                "status": "已结束",
                "category1": "ethics",
                "category2": "ethics-cultivation",
                "dimension": "ethics"
        },
        {
                "id": 132,
                "title": "作业设计与评价改革培训",
                "level": "校级培训",
                "year": 2025,
                "month": 6,
                "certificate": true,
                "hours": 5,
                "status": "已结束",
                "category1": "ability",
                "category2": "ability-design",
                "dimension": "ability"
        },
        {
                "id": 133,
                "title": "新课标下的课堂教学创新培训",
                "level": "市级培训",
                "year": 2023,
                "month": 4,
                "certificate": true,
                "hours": 11,
                "status": "已结束",
                "category1": "ability",
                "category2": "ability-design",
                "dimension": "ability"
        },
        {
                "id": 134,
                "title": "STEM教育理念与实践培训",
                "level": "校级培训",
                "year": 2024,
                "month": 2,
                "certificate": true,
                "hours": 37,
                "status": "已结束",
                "category1": "ethics",
                "category2": "ethics-concept",
                "dimension": "ethics"
        },
        {
                "id": 135,
                "title": "STEM教育理念与实践培训",
                "level": "市级培训",
                "year": 2024,
                "month": 1,
                "certificate": true,
                "hours": 8,
                "status": "已结束",
                "category1": "ethics",
                "category2": "ethics-concept",
                "dimension": "ethics"
        },
        {
                "id": 136,
                "title": "STEM教育理念与实践培训",
                "level": "市级培训",
                "year": 2024,
                "month": 9,
                "certificate": true,
                "hours": 15,
                "status": "已结束",
                "category1": "ethics",
                "category2": "ethics-concept",
                "dimension": "ethics"
        },
        {
                "id": 137,
                "title": "STEM教育理念与实践培训",
                "level": "国家级培训",
                "year": 2024,
                "month": 5,
                "certificate": true,
                "hours": 12,
                "status": "已结束",
                "category1": "ethics",
                "category2": "ethics-concept",
                "dimension": "ethics"
        },
        {
                "id": 138,
                "title": "教师信息技术应用能力提升培训",
                "level": "市级培训",
                "year": 2023,
                "month": 1,
                "certificate": true,
                "hours": 28,
                "status": "已结束",
                "category1": "digital",
                "category2": "digital-tech",
                "dimension": "digital"
        },
        {
                "id": 139,
                "title": "STEM教育理念与实践培训",
                "level": "校级培训",
                "year": 2023,
                "month": 8,
                "certificate": true,
                "hours": 28,
                "status": "已结束",
                "category1": "ethics",
                "category2": "ethics-concept",
                "dimension": "ethics"
        },
        {
                "id": 140,
                "title": "校本课程开发与实施培训",
                "level": "其它",
                "year": 2023,
                "month": 10,
                "certificate": true,
                "hours": 36,
                "status": "已结束",
                "category1": "ability",
                "category2": "ability-development",
                "dimension": "ability"
        },
        {
                "id": 141,
                "title": "作业设计与评价改革培训",
                "level": "国家级培训",
                "year": 2023,
                "month": 2,
                "certificate": true,
                "hours": 24,
                "status": "已结束",
                "category1": "ability",
                "category2": "ability-design",
                "dimension": "ability"
        },
        {
                "id": 142,
                "title": "跨学科教学融合实践研修",
                "level": "市级培训",
                "year": 2025,
                "month": 8,
                "certificate": true,
                "hours": 27,
                "status": "已结束",
                "category1": "knowledge",
                "category2": "knowledge-subject",
                "dimension": "knowledge"
        },
        {
                "id": 143,
                "title": "学科核心考点解析与教学策略培训",
                "level": "国家级培训",
                "year": 2025,
                "month": 1,
                "certificate": true,
                "hours": 36,
                "status": "已结束",
                "category1": "knowledge",
                "category2": "knowledge-subject",
                "dimension": "knowledge"
        },
        {
                "id": 144,
                "title": "教师信息技术应用能力提升培训",
                "level": "校级培训",
                "year": 2024,
                "month": 2,
                "certificate": true,
                "hours": 15,
                "status": "已结束",
                "category1": "digital",
                "category2": "digital-tech",
                "dimension": "digital"
        },
        {
                "id": 145,
                "title": "教师信息技术应用能力提升培训",
                "level": "省级培训",
                "year": 2025,
                "month": 7,
                "certificate": true,
                "hours": 4,
                "status": "已结束",
                "category1": "digital",
                "category2": "digital-tech",
                "dimension": "digital"
        },
        {
                "id": 146,
                "title": "心理健康教育与学生辅导培训",
                "level": "市级培训",
                "year": 2023,
                "month": 10,
                "certificate": true,
                "hours": 26,
                "status": "已结束",
                "category1": "ability",
                "category2": "ability-management",
                "dimension": "ability"
        },
        {
                "id": 147,
                "title": "STEM教育理念与实践培训",
                "level": "其它",
                "year": 2025,
                "month": 4,
                "certificate": true,
                "hours": 7,
                "status": "已结束",
                "category1": "ethics",
                "category2": "ethics-concept",
                "dimension": "ethics"
        },
        {
                "id": 148,
                "title": "新课标下的课堂教学创新培训",
                "level": "国家级培训",
                "year": 2025,
                "month": 5,
                "certificate": true,
                "hours": 9,
                "status": "已结束",
                "category1": "ability",
                "category2": "ability-design",
                "dimension": "ability"
        },
        {
                "id": 149,
                "title": "教育科研方法与论文写作培训",
                "level": "省级培训",
                "year": 2023,
                "month": 6,
                "certificate": true,
                "hours": 34,
                "status": "已结束",
                "category1": "ability",
                "category2": "ability-research",
                "dimension": "ability"
        },
        {
                "id": 150,
                "title": "校本课程开发与实施培训",
                "level": "省级培训",
                "year": 2025,
                "month": 1,
                "certificate": true,
                "hours": 36,
                "status": "已结束",
                "category1": "ability",
                "category2": "ability-development",
                "dimension": "ability"
        },
        {
                "id": 151,
                "title": "师德师风建设专题培训",
                "level": "省级培训",
                "year": 2024,
                "month": 12,
                "certificate": true,
                "hours": 32,
                "status": "已结束",
                "category1": "ethics",
                "category2": "ethics-cultivation",
                "dimension": "ethics"
        },
        {
                "id": 152,
                "title": "新课标下的课堂教学创新培训",
                "level": "校级培训",
                "year": 2024,
                "month": 8,
                "certificate": true,
                "hours": 19,
                "status": "已结束",
                "category1": "ability",
                "category2": "ability-design",
                "dimension": "ability"
        },
        {
                "id": 153,
                "title": "作业设计与评价改革培训",
                "level": "其它",
                "year": 2023,
                "month": 10,
                "certificate": true,
                "hours": 24,
                "status": "已结束",
                "category1": "ability",
                "category2": "ability-design",
                "dimension": "ability"
        },
        {
                "id": 154,
                "title": "教育科研方法与论文写作培训",
                "level": "其它",
                "year": 2023,
                "month": 10,
                "certificate": true,
                "hours": 47,
                "status": "已结束",
                "category1": "ability",
                "category2": "ability-research",
                "dimension": "ability"
        },
        {
                "id": 155,
                "title": "教师信息技术应用能力提升培训",
                "level": "校级培训",
                "year": 2025,
                "month": 2,
                "certificate": true,
                "hours": 29,
                "status": "已结束",
                "category1": "digital",
                "category2": "digital-tech",
                "dimension": "digital"
        },
        {
                "id": 156,
                "title": "心理健康教育与学生辅导培训",
                "level": "省级培训",
                "year": 2024,
                "month": 1,
                "certificate": true,
                "hours": 25,
                "status": "已结束",
                "category1": "ability",
                "category2": "ability-management",
                "dimension": "ability"
        },
        {
                "id": 157,
                "title": "特殊学生教育与帮扶培训",
                "level": "国家级培训",
                "year": 2023,
                "month": 6,
                "certificate": true,
                "hours": 34,
                "status": "已结束",
                "category1": "ability",
                "category2": "ability-management",
                "dimension": "ability"
        },
        {
                "id": 158,
                "title": "STEM教育理念与实践培训",
                "level": "国家级培训",
                "year": 2024,
                "month": 5,
                "certificate": true,
                "hours": 27,
                "status": "已结束",
                "category1": "ethics",
                "category2": "ethics-concept",
                "dimension": "ethics"
        },
        {
                "id": 159,
                "title": "家校共育沟通技巧培训",
                "level": "省级培训",
                "year": 2025,
                "month": 6,
                "certificate": true,
                "hours": 17,
                "status": "已结束",
                "category1": "ability",
                "category2": "ability-management",
                "dimension": "ability"
        },
        {
                "id": 160,
                "title": "教育科研方法与论文写作培训",
                "level": "校级培训",
                "year": 2023,
                "month": 7,
                "certificate": true,
                "hours": 16,
                "status": "已结束",
                "category1": "ability",
                "category2": "ability-research",
                "dimension": "ability"
        },
        {
                "id": 161,
                "title": "教育科研方法与论文写作培训",
                "level": "国家级培训",
                "year": 2025,
                "month": 8,
                "certificate": true,
                "hours": 22,
                "status": "已结束",
                "category1": "ability",
                "category2": "ability-research",
                "dimension": "ability"
        },
        {
                "id": 162,
                "title": "家校共育沟通技巧培训",
                "level": "校级培训",
                "year": 2025,
                "month": 3,
                "certificate": true,
                "hours": 11,
                "status": "已结束",
                "category1": "ability",
                "category2": "ability-management",
                "dimension": "ability"
        },
        {
                "id": 163,
                "title": "家校共育沟通技巧培训",
                "level": "省级培训",
                "year": 2023,
                "month": 8,
                "certificate": true,
                "hours": 45,
                "status": "已结束",
                "category1": "ability",
                "category2": "ability-management",
                "dimension": "ability"
        },
        {
                "id": 164,
                "title": "跨学科教学融合实践研修",
                "level": "国家级培训",
                "year": 2025,
                "month": 12,
                "certificate": true,
                "hours": 42,
                "status": "已结束",
                "category1": "knowledge",
                "category2": "knowledge-subject",
                "dimension": "knowledge"
        },
        {
                "id": 165,
                "title": "师德师风建设专题培训",
                "level": "国家级培训",
                "year": 2023,
                "month": 5,
                "certificate": true,
                "hours": 9,
                "status": "已结束",
                "category1": "ethics",
                "category2": "ethics-cultivation",
                "dimension": "ethics"
        },
        {
                "id": 166,
                "title": "跨学科教学融合实践研修",
                "level": "校级培训",
                "year": 2024,
                "month": 9,
                "certificate": true,
                "hours": 28,
                "status": "已结束",
                "category1": "knowledge",
                "category2": "knowledge-subject",
                "dimension": "knowledge"
        },
        {
                "id": 167,
                "title": "心理健康教育与学生辅导培训",
                "level": "校级培训",
                "year": 2024,
                "month": 9,
                "certificate": true,
                "hours": 33,
                "status": "已结束",
                "category1": "ability",
                "category2": "ability-management",
                "dimension": "ability"
        },
        {
                "id": 168,
                "title": "心理健康教育与学生辅导培训",
                "level": "国家级培训",
                "year": 2024,
                "month": 11,
                "certificate": true,
                "hours": 31,
                "status": "已结束",
                "category1": "ability",
                "category2": "ability-management",
                "dimension": "ability"
        },
        {
                "id": 169,
                "title": "新课标下的课堂教学创新培训",
                "level": "其它",
                "year": 2025,
                "month": 9,
                "certificate": true,
                "hours": 36,
                "status": "已结束",
                "category1": "ability",
                "category2": "ability-design",
                "dimension": "ability"
        },
        {
                "id": 170,
                "title": "跨学科教学融合实践研修",
                "level": "国家级培训",
                "year": 2023,
                "month": 8,
                "certificate": true,
                "hours": 48,
                "status": "已结束",
                "category1": "knowledge",
                "category2": "knowledge-subject",
                "dimension": "knowledge"
        },
        {
                "id": 171,
                "title": "跨学科教学融合实践研修",
                "level": "省级培训",
                "year": 2024,
                "month": 4,
                "certificate": true,
                "hours": 48,
                "status": "已结束",
                "category1": "knowledge",
                "category2": "knowledge-subject",
                "dimension": "knowledge"
        },
        {
                "id": 172,
                "title": "心理健康教育与学生辅导培训",
                "level": "国家级培训",
                "year": 2024,
                "month": 4,
                "certificate": true,
                "hours": 10,
                "status": "已结束",
                "category1": "ability",
                "category2": "ability-management",
                "dimension": "ability"
        },
        {
                "id": 173,
                "title": "班主任班级管理能力研修",
                "level": "其它",
                "year": 2025,
                "month": 3,
                "certificate": true,
                "hours": 45,
                "status": "已结束",
                "category1": "ability",
                "category2": "ability-management",
                "dimension": "ability"
        },
        {
                "id": 174,
                "title": "家校共育沟通技巧培训",
                "level": "校级培训",
                "year": 2023,
                "month": 11,
                "certificate": true,
                "hours": 22,
                "status": "已结束",
                "category1": "ability",
                "category2": "ability-management",
                "dimension": "ability"
        },
        {
                "id": 175,
                "title": "作业设计与评价改革培训",
                "level": "市级培训",
                "year": 2024,
                "month": 2,
                "certificate": true,
                "hours": 17,
                "status": "已结束",
                "category1": "ability",
                "category2": "ability-design",
                "dimension": "ability"
        },
        {
                "id": 176,
                "title": "班主任班级管理能力研修",
                "level": "省级培训",
                "year": 2025,
                "month": 6,
                "certificate": true,
                "hours": 5,
                "status": "已结束",
                "category1": "ability",
                "category2": "ability-management",
                "dimension": "ability"
        },
        {
                "id": 177,
                "title": "家校共育沟通技巧培训",
                "level": "市级培训",
                "year": 2023,
                "month": 6,
                "certificate": true,
                "hours": 20,
                "status": "已结束",
                "category1": "ability",
                "category2": "ability-management",
                "dimension": "ability"
        },
        {
                "id": 178,
                "title": "特殊学生教育与帮扶培训",
                "level": "省级培训",
                "year": 2023,
                "month": 5,
                "certificate": true,
                "hours": 36,
                "status": "已结束",
                "category1": "ability",
                "category2": "ability-management",
                "dimension": "ability"
        },
        {
                "id": 179,
                "title": "核心素养导向的教学设计培训",
                "level": "其它",
                "year": 2023,
                "month": 11,
                "certificate": true,
                "hours": 48,
                "status": "已结束",
                "category1": "ability",
                "category2": "ability-design",
                "dimension": "ability"
        },
        {
                "id": 180,
                "title": "跨学科教学融合实践研修",
                "level": "市级培训",
                "year": 2025,
                "month": 4,
                "certificate": true,
                "hours": 37,
                "status": "已结束",
                "category1": "knowledge",
                "category2": "knowledge-subject",
                "dimension": "knowledge"
        },
        {
                "id": 181,
                "title": "新课标下的课堂教学创新培训",
                "level": "市级培训",
                "year": 2025,
                "month": 11,
                "certificate": true,
                "hours": 11,
                "status": "已结束",
                "category1": "ability",
                "category2": "ability-design",
                "dimension": "ability"
        },
        {
                "id": 182,
                "title": "核心素养导向的教学设计培训",
                "level": "其它",
                "year": 2023,
                "month": 7,
                "certificate": true,
                "hours": 8,
                "status": "已结束",
                "category1": "ability",
                "category2": "ability-design",
                "dimension": "ability"
        },
        {
                "id": 183,
                "title": "校本课程开发与实施培训",
                "level": "市级培训",
                "year": 2025,
                "month": 11,
                "certificate": true,
                "hours": 33,
                "status": "已结束",
                "category1": "ability",
                "category2": "ability-development",
                "dimension": "ability"
        },
        {
                "id": 184,
                "title": "师德师风建设专题培训",
                "level": "国家级培训",
                "year": 2023,
                "month": 11,
                "certificate": true,
                "hours": 13,
                "status": "已结束",
                "category1": "ethics",
                "category2": "ethics-cultivation",
                "dimension": "ethics"
        },
        {
                "id": 185,
                "title": "校本课程开发与实施培训",
                "level": "其它",
                "year": 2025,
                "month": 7,
                "certificate": true,
                "hours": 29,
                "status": "已结束",
                "category1": "ability",
                "category2": "ability-development",
                "dimension": "ability"
        },
        {
                "id": 186,
                "title": "家校共育沟通技巧培训",
                "level": "其它",
                "year": 2025,
                "month": 8,
                "certificate": true,
                "hours": 38,
                "status": "已结束",
                "category1": "ability",
                "category2": "ability-management",
                "dimension": "ability"
        },
        {
                "id": 187,
                "title": "跨学科教学融合实践研修",
                "level": "省级培训",
                "year": 2024,
                "month": 2,
                "certificate": true,
                "hours": 46,
                "status": "已结束",
                "category1": "knowledge",
                "category2": "knowledge-subject",
                "dimension": "knowledge"
        },
        {
                "id": 188,
                "title": "家校共育沟通技巧培训",
                "level": "其它",
                "year": 2024,
                "month": 7,
                "certificate": true,
                "hours": 21,
                "status": "已结束",
                "category1": "ability",
                "category2": "ability-management",
                "dimension": "ability"
        },
        {
                "id": 189,
                "title": "教育科研方法与论文写作培训",
                "level": "国家级培训",
                "year": 2024,
                "month": 2,
                "certificate": true,
                "hours": 34,
                "status": "已结束",
                "category1": "ability",
                "category2": "ability-research",
                "dimension": "ability"
        },
        {
                "id": 190,
                "title": "教育科研方法与论文写作培训",
                "level": "国家级培训",
                "year": 2025,
                "month": 9,
                "certificate": true,
                "hours": 28,
                "status": "已结束",
                "category1": "ability",
                "category2": "ability-research",
                "dimension": "ability"
        },
        {
                "id": 191,
                "title": "教师信息技术应用能力提升培训",
                "level": "市级培训",
                "year": 2023,
                "month": 9,
                "certificate": true,
                "hours": 25,
                "status": "已结束",
                "category1": "digital",
                "category2": "digital-tech",
                "dimension": "digital"
        },
        {
                "id": 192,
                "title": "班主任班级管理能力研修",
                "level": "市级培训",
                "year": 2024,
                "month": 11,
                "certificate": true,
                "hours": 26,
                "status": "已结束",
                "category1": "ability",
                "category2": "ability-management",
                "dimension": "ability"
        },
        {
                "id": 193,
                "title": "新课标下的课堂教学创新培训",
                "level": "其它",
                "year": 2025,
                "month": 5,
                "certificate": true,
                "hours": 45,
                "status": "已结束",
                "category1": "ability",
                "category2": "ability-design",
                "dimension": "ability"
        },
        {
                "id": 194,
                "title": "作业设计与评价改革培训",
                "level": "省级培训",
                "year": 2023,
                "month": 3,
                "certificate": true,
                "hours": 15,
                "status": "已结束",
                "category1": "ability",
                "category2": "ability-design",
                "dimension": "ability"
        },
        {
                "id": 195,
                "title": "班主任班级管理能力研修",
                "level": "其它",
                "year": 2023,
                "month": 2,
                "certificate": true,
                "hours": 25,
                "status": "已结束",
                "category1": "ability",
                "category2": "ability-management",
                "dimension": "ability"
        },
        {
                "id": 196,
                "title": "STEM教育理念与实践培训",
                "level": "国家级培训",
                "year": 2023,
                "month": 12,
                "certificate": true,
                "hours": 37,
                "status": "已结束",
                "category1": "ethics",
                "category2": "ethics-concept",
                "dimension": "ethics"
        },
        {
                "id": 197,
                "title": "特殊学生教育与帮扶培训",
                "level": "其它",
                "year": 2024,
                "month": 4,
                "certificate": true,
                "hours": 17,
                "status": "已结束",
                "category1": "ability",
                "category2": "ability-management",
                "dimension": "ability"
        },
        {
                "id": 198,
                "title": "学科核心考点解析与教学策略培训",
                "level": "校级培训",
                "year": 2023,
                "month": 2,
                "certificate": true,
                "hours": 11,
                "status": "已结束",
                "category1": "knowledge",
                "category2": "knowledge-subject",
                "dimension": "knowledge"
        },
        {
                "id": 199,
                "title": "学科核心考点解析与教学策略培训",
                "level": "国家级培训",
                "year": 2024,
                "month": 10,
                "certificate": true,
                "hours": 19,
                "status": "已结束",
                "category1": "knowledge",
                "category2": "knowledge-subject",
                "dimension": "knowledge"
        },
        {
                "id": 200,
                "title": "校本课程开发与实施培训",
                "level": "国家级培训",
                "year": 2024,
                "month": 8,
                "certificate": true,
                "hours": 37,
                "status": "已结束",
                "category1": "ability",
                "category2": "ability-development",
                "dimension": "ability"
        }
];